# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'try2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 842)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Input_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Input_label.setEnabled(True)
        self.Input_label.setObjectName("Input_label")
        self.verticalLayout.addWidget(self.Input_label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(800, 650, 221, 91))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.start = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.start.setObjectName("start")
        self.verticalLayout_4.addWidget(self.start)
        self.choose_file = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.choose_file.setObjectName("choose_file")
        self.verticalLayout_4.addWidget(self.choose_file)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(0, 670, 801, 61))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.bar = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.bar.setContentsMargins(0, 0, 0, 0)
        self.bar.setObjectName("bar")
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_5)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.bar.addWidget(self.progressBar)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(810, 0, 211, 71))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.all_people = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.all_people.setObjectName("all_people")
        self.verticalLayout_3.addWidget(self.all_people, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 640, 211, 31))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.remaining_time = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.remaining_time.setObjectName("remaining_time")
        self.verticalLayout_6.addWidget(self.remaining_time)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(810, 70, 211, 81))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.now_people = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.now_people.setObjectName("now_people")
        self.verticalLayout_5.addWidget(self.now_people, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(810, 150, 211, 81))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.no_mask_rate = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.no_mask_rate.setObjectName("no_mask_rate")
        self.verticalLayout_7.addWidget(self.no_mask_rate, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 2, 2))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(0, 30, 801, 601))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.imageshow = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.imageshow.setStyleSheet("border-color: rgb(85, 85, 127);")
        self.imageshow.setAlignment(Qt.AlignTop)
        self.imageshow.setAlignment(Qt.AlignLeft)
        self.imageshow.setScaledContents(True)
        self.imageshow.setObjectName("imageshow")
        self.verticalLayout_8.addWidget(self.imageshow)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(810, 330, 211, 301))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setCurrentRow(0)
        self.listWidget.setViewMode(QListView.ListMode)
        self.listWidget.setSpacing(3)
        self.listWidget.setItemAlignment(QtCore.Qt.AlignCenter)
        self.listWidget.setEnabled(True)
        # self.listWidget.addItem("lomp4-detect001.jpg")
        # self.listWidget.addItem("lomp4-detect001.jpg")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(0, 730, 1021, 91))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.listWidget_2 = QtWidgets.QListWidget(self.verticalLayoutWidget_13)
        self.listWidget_2.setObjectName("listWidget_2")
        self.listWidget_2.setCurrentRow(0)
        self.listWidget_2.setViewMode(QListView.ListMode)
        self.listWidget_2.setSpacing(3)
        self.listWidget_2.setItemAlignment(QtCore.Qt.AlignCenter)
        self.listWidget_2.setEnabled(True)
        self.verticalLayout_12.addWidget(self.listWidget_2)
        

        self.horizontalLayout.addWidget(self.listWidget)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(220, 640, 211, 31))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.FPS = QtWidgets.QLabel(self.verticalLayoutWidget_11)
        self.FPS.setObjectName("FPS")
        self.verticalLayout_10.addWidget(self.FPS, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(809, 280, 211, 41))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(430, 640, 211, 31))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.FPS_2 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.FPS_2.setObjectName("FPS_2")
        self.verticalLayout_11.addWidget(self.FPS_2, 0, QtCore.Qt.AlignHCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "監視系統影像分析"))
        self.Input_label.setText(_translate("MainWindow", "目前輸入: "))
        self.start.setText(_translate("MainWindow", "開始分析"))
        self.choose_file.setText(_translate("MainWindow", "選擇檔案"))
        self.all_people.setText(_translate("MainWindow", "影片內總人數:"))
        self.remaining_time.setText(_translate("MainWindow", "預計剩餘時間: "))
        self.now_people.setText(_translate("MainWindow", "當前畫面總人數"))
        self.no_mask_rate.setText(_translate("MainWindow", "未戴口罩比率"))
        self.FPS.setText(_translate("MainWindow", "FPS:"))
        self.label.setText(_translate("MainWindow", "已儲存人臉"))
        self.FPS_2.setText(_translate("MainWindow", "剩餘張數:"))

